// Lexer.cpp generated by reflex 3.2.11 from /home/master/projects/thue/src/neothue.l

#define REFLEX_VERSION "3.2.11"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_YYLTYPE
#undef REFLEX_OPTION_YYSTYPE
#undef REFLEX_OPTION_bison_cc
#undef REFLEX_OPTION_bison_cc_namespace
#undef REFLEX_OPTION_bison_cc_parser
#undef REFLEX_OPTION_bison_complete
#undef REFLEX_OPTION_bison_locations
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_noyywrap
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_token_eof
#undef REFLEX_OPTION_token_type

#define REFLEX_OPTION_YYLTYPE             nthue::location
#define REFLEX_OPTION_YYSTYPE             nthue::ParserImplementation::semantic_type
#define REFLEX_OPTION_bison_cc            true
#define REFLEX_OPTION_bison_cc_namespace  nthue
#define REFLEX_OPTION_bison_cc_parser     ParserImplementation
#define REFLEX_OPTION_bison_complete      true
#define REFLEX_OPTION_bison_locations     true
#define REFLEX_OPTION_header_file         "Lexer.h"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           nthue
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "Lexer.cpp"
#define REFLEX_OPTION_token_eof           nthue::ParserImplementation::symbol_type(0, location())
#define REFLEX_OPTION_token_type          nthue::ParserImplementation::symbol_type

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "/home/master/projects/thue/src/neothue.l"

    #include <iostream>
    #include <algorithm>
    #include "Token.h"
    #include "ParserImplementation.h"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace nthue {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  static const int UNQSTR = 1;
  static const int SQSTR = 2;
  static const int DQSTR = 3;
  std::string filename;
  // bison-complete bison-locations: location() returns lexeme location
  virtual nthue::location location(void)
  {
    nthue::location yylloc;
    yylloc.begin.filename = &filename;
    yylloc.begin.line = static_cast<unsigned int>(matcher().lineno());
    yylloc.begin.column = static_cast<unsigned int>(matcher().columno()+1);
    yylloc.end.filename = &filename;
    yylloc.end.line = static_cast<unsigned int>(matcher().lineno_end());
    yylloc.end.column = static_cast<unsigned int>(matcher().columno_end()+2);
    return yylloc;
  }
  // the bison-complete lexer function defined by SECTION 2
  virtual nthue::ParserImplementation::symbol_type lex(void);
};

} // namespace nthue

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 8 "/home/master/projects/thue/src/neothue.l"

    using nthue::position;

    static position yypos;
    static position yytemp;
    static std::string yybuf;


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON C++                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

nthue::ParserImplementation::symbol_type nthue::Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)(['])|([\"])|((?:[;][^\\x0a]*))|((?:[\\x09-\\x0d\\x20])+)|([=])|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  static const char *REGEX_UNQSTR = "(?m)((?:[^\\x09-\\x0d\\x20;=]+))";
  static const reflex::Pattern PATTERN_UNQSTR(REGEX_UNQSTR);
  static const char *REGEX_SQSTR = "(?m)((?:[^'\\x5c]*))|([\\x5c]['])|([\\x5c].)|(['])";
  static const reflex::Pattern PATTERN_SQSTR(REGEX_SQSTR);
  static const char *REGEX_DQSTR = "(?m)((?:[^\"\\x5c]*))|([\\x5c][\"])|([\\x5c].)|([\"])";
  static const reflex::Pattern PATTERN_DQSTR(REGEX_DQSTR);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
    switch (start())
    {
      case INITIAL:
        matcher().pattern(PATTERN_INITIAL);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return nthue::ParserImplementation::symbol_type(0, location());
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule /home/master/projects/thue/src/neothue.l:37: ['] :
#line 37 "/home/master/projects/thue/src/neothue.l"
start(SQSTR); yytemp = location().begin;
            break;
          case 2: // rule /home/master/projects/thue/src/neothue.l:51: ["] :
#line 51 "/home/master/projects/thue/src/neothue.l"
start(DQSTR); yytemp = location().begin;
            break;
          case 3: // rule /home/master/projects/thue/src/neothue.l:71: {comment} :
#line 71 "/home/master/projects/thue/src/neothue.l"
            break;
          case 4: // rule /home/master/projects/thue/src/neothue.l:72: {ws}+ :
#line 72 "/home/master/projects/thue/src/neothue.l"
            break;
          case 5: // rule /home/master/projects/thue/src/neothue.l:73: [=] :
#line 73 "/home/master/projects/thue/src/neothue.l"
return ParserImplementation::make_SEPARATOR(location());
            break;
          case 6: // rule /home/master/projects/thue/src/neothue.l:74: . :
#line 74 "/home/master/projects/thue/src/neothue.l"
start(UNQSTR); matcher().unput(chr());
            break;
        }
        break;
      case UNQSTR:
        matcher().pattern(PATTERN_UNQSTR);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return nthue::ParserImplementation::symbol_type(0, location());
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule /home/master/projects/thue/src/neothue.l:65: {unquoted_str} :
#line 65 "/home/master/projects/thue/src/neothue.l"
{
    start(INITIAL);

    return ParserImplementation::make_STRING(str(), location());
}

            break;
        }
        break;
      case SQSTR:
        matcher().pattern(PATTERN_SQSTR);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return nthue::ParserImplementation::symbol_type(0, location());
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule /home/master/projects/thue/src/neothue.l:38: {sq_str} :
#line 38 "/home/master/projects/thue/src/neothue.l"
yybuf += str();
            break;
          case 2: // rule /home/master/projects/thue/src/neothue.l:39: [\\]['] :
#line 39 "/home/master/projects/thue/src/neothue.l"
yybuf += '\'';
            break;
          case 3: // rule /home/master/projects/thue/src/neothue.l:40: [\\]. :
#line 40 "/home/master/projects/thue/src/neothue.l"
yybuf += text();
            break;
          case 4: // rule /home/master/projects/thue/src/neothue.l:41: ['] :
#line 41 "/home/master/projects/thue/src/neothue.l"
{
    yybuf.clear();
    start(INITIAL);

    nthue::location pos = location();
    pos.begin = yytemp;

    return ParserImplementation::make_STRING(yybuf, pos);
}

            break;
        }
        break;
      case DQSTR:
        matcher().pattern(PATTERN_DQSTR);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return nthue::ParserImplementation::symbol_type(0, location());
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule /home/master/projects/thue/src/neothue.l:52: {dq_str} :
#line 52 "/home/master/projects/thue/src/neothue.l"
yybuf += str();
            break;
          case 2: // rule /home/master/projects/thue/src/neothue.l:53: [\\]["] :
#line 53 "/home/master/projects/thue/src/neothue.l"
yybuf += '"';
            break;
          case 3: // rule /home/master/projects/thue/src/neothue.l:54: [\\]. :
#line 54 "/home/master/projects/thue/src/neothue.l"
yybuf += text();
            break;
          case 4: // rule /home/master/projects/thue/src/neothue.l:55: ["] :
#line 55 "/home/master/projects/thue/src/neothue.l"
{
    yybuf.clear();
    start(INITIAL);

    nthue::location pos = location();
    pos.begin = yytemp;

    return ParserImplementation::make_STRING(yybuf, pos);
}

            break;
        }
        break;
      default:
        start(0);
    }
  }
}
